# Generated by Django 4.2.15 on 2024-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0002_user_last_login_alter_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
