# Generated by Django 4.2.15 on 2024-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0003_userlist_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='username',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
