# Generated by Django 4.2.15 on 2024-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0005_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
    ]
