# Generated by Django 4.2.15 on 2024-08-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0008_alter_alarm_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
