# Generated by Django 4.2.15 on 2024-08-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0009_delete_alarm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
