# Generated by Django 4.2.15 on 2024-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0012_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='user',
        ),
        migrations.AddField(
            model_name='alarm',
            name='user_id',
            field=models.CharField(default='default_user', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='days',
            field=models.JSONField(),
        ),
    ]
