# Generated by Django 4.2.15 on 2024-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0013_remove_alarm_user_alarm_user_id_alter_alarm_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
