# Generated by Django 4.2.15 on 2024-08-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0014_alter_alarm_time_alter_alarm_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_code', models.CharField(max_length=100)),
                ('pill_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ict.userlist')),
            ],
        ),
    ]
