# Generated by Django 4.2.15 on 2024-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict', '0015_favoritepill'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='usage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
